context:
  handler:
    name: env-context
backend:
  manage:
    handler:
      name: express
  api:
    handler:
      name: graphql-api
platforms:
  web:
    depends_on:
      - backend.api
      - backend.manage
    handler:
      name: express-ssr
